config/routes.rb
Rails.application.routes.draw do
  get 'site/index'
get 'sign_up' => 'users#new', as: 'sign_up'
resources :users
root to: 'site#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
attr_accessor :password
validates_confirmation_of :password
validates_presence_of :password, on: :create
validates_presence_of :email
validates_uniqueness_of :email
before_save :hash_password

def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
    user
    else
    nil
    end
    end
    
    def hash_password
    if password.present?
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
@user = User.new
end

def create
@user = User.new(user_parameters)
respond_to do |format|
if @user.save
format.html { redirect_to root_path, notice: "Successfully signed up" }
else
format.html { render :new, error: "Invalid input", status: :unprocessable_entity }
end
end
end

private

def user_parameters
params.require(:user).permit(:email, :password, :password_confirmation)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleAuth</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= link_to "Sign up", sign_up_path %>

    <%= yield %>
  </body>
</html>

app/views/site/index.html.erb
<h1>Site#index</h1>
<p>Find me in app/views/site/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<h1>Sign Up</h1>
<%= form_for @user do |f| %>
<% if @user.errors.any? %>
<div class="error_messages">
<ul>
<% for message in @user.errors.full_messages %>
<li><%= message %></li>
<% end %>
</ul>
</div>
<% end %>
<p>
<%= f.label :email %><br />
<%= f.text_field :email %>
</p>
<p>
<%= f.label :password %><br />
<%= f.password_field :password %>
</p>
<p>
<%= f.label :password_confirmation %><br />
<%= f.password_field :password_confirmation %>
</p>
<p class="button"><%= f.submit %></p>
<% end %>